version: "3"

volumes: 
    vol-dados-mysql:

networks: 
    rede-backend:
    rede-frontend:

services:

    mysql-servico:
        image: "mysql:5.7"
        container_name: mysql-servico
        volumes:
            - vol-dados-mysql:/var/lib/mysql
            - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d      
        networks:
            - rede-backend
        environment:
            - MYSQL_ROOT_PASSWORD=numsey
            - bind-address=0.0.0.0

    dot31-lista-comdb-mysql-compose-app:
        container_name: dot31-lista-comdb-mysql-compose-app
        build:
            context: .
            dockerfile: Dockerfile
        image: dot31-lista-comdb-mysql-compose
        networks:
            - rede-backend
            - rede-frontend
        ports:
            - 5000:80
        environment:
            - DBHOST=mysql-servico
        depends_on:
            - mysql-servico