FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN mkdir /app

WORKDIR /app

COPY mvc1.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o dist

EXPOSE 5000/tcp

CMD ["dotnet", "dist/mvc1.dll"]
